// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Применение настройки вида: значение — на `<html>`, правило — в CSS.
 */
export type Apply = { "to": "attr", name: string, } | { "to": "var", name: string, unit: string, };
