// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an appearance setting is applied: the value goes on `<html>`, the rule into CSS.
 */
export type Apply = { "to": "attr", name: string, } | { "to": "var", name: string, unit: string, };
