// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteId } from "./NoteId";

/**
 * A link to a note from another note.
 */
export type Backlink = { 
/**
 * The linking note.
 */
from: NoteId, 
/**
 * The link anchor as written.
 */
anchor: string | null, 
/**
 * The section of the note the anchor leads to: the heading `id` (the
 * heading HTML is in `Rendered::headings`) and its text (a formula as
 * source); no anchor or the section was not found - `None`.
 */
section: string | null, heading: string | null, };
