// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteId } from "./NoteId";

/**
 * Ссылка на заметку из другой заметки.
 */
export type Backlink = { from: NoteId, anchor: string | null, 
/**
 * Раздел заметки, куда ведёт якорь: `id` заголовка (HTML заголовка —
 * в `Rendered::headings`) и его текст (формула — исходником); якоря
 * нет или раздел не нашёлся — `None`.
 */
section: string | null, heading: string | null, };
