// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chapter } from "./Chapter";

/**
 * Какая глава показана и где остальные.
 */
export type BookView = { 
/**
 * Номер показанной главы (с нуля).
 */
chapter: number, chapters: Array<Chapter>, 
/**
 * Якорь (`id` или `data-k-anchor`) → номер главы. `id` уникальны; из
 * одинаковых `data-k-anchor` («Итоги» в каждой главе) — первый.
 */
anchors: { [key in string]: number }, };
