// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chapter } from "./Chapter";

/**
 * Which chapter is shown and where the others are.
 */
export type BookView = { 
/**
 * The number of the shown chapter (from zero).
 */
chapter: number, chapters: Array<Chapter>, 
/**
 * Anchor (`id` or `data-k-anchor`) -> chapter number. `id`s are unique; of
 * equal `data-k-anchor`s ("Summary" in every chapter) the first one wins.
 */
anchors: { [key in string]: number }, };
