// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Событие `change` потока `GET /api/events`: файлы хранилища изменились
 * (пачкой, см. `notes_core::watch`) — клиенту пора сверить версию заметки.
 */
export type ChangeEvent = { 
/**
 * Растёт с каждым изменением.
 */
seq: number, 
/**
 * Изменившиеся файлы хранилища; пусто — неизвестно какие (проверить всё).
 */
paths: Array<string>, };
