// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A change of vault files (batched, see `notes_core::watch`): time for the
 * client to check the note version.
 */
export type ChangeEvent = { 
/**
 * Grows with every change.
 */
seq: number, 
/**
 * The changed vault files; empty means unknown (check everything).
 */
paths: Array<string>, };
