// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whose chapter the node is and where it leads.
 */
export type ChapterOf = { 
/**
 * Book path.
 */
book: string, 
/**
 * `id` of the chapter heading on the book page.
 */
anchor: string, };
