// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Глава в списке глав.
 */
export type Chapter = { 
/**
 * Номер главы (`data-num`) или пусто.
 */
num: string, 
/**
 * Название без номера.
 */
title: string, 
/**
 * `id` заголовка главы.
 */
id: string, };
