// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A chapter in the chapter list.
 */
export type Chapter = { 
/**
 * The chapter number (`data-num`) or empty.
 */
num: string, 
/**
 * The title without the number.
 */
title: string, 
/**
 * The `id` of the chapter heading.
 */
id: string, };
