// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Чья глава вершина и куда она ведёт.
 */
export type ChapterOf = { 
/**
 * Путь книги.
 */
book: string, 
/**
 * `id` заголовка главы на странице книги.
 */
anchor: string, };
