// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagSeverity } from "./DiagSeverity";

export type Diagnostic = { severity: DiagSeverity, message: string, 
/**
 * The file from the vault root (`/Network/SSH.typ`) or a package (`@preview/cetz:0.4.2/...`).
 */
file: string | null, 
/**
 * Line and column, starting at one.
 */
line: number | null, column: number | null, hints: Array<string>, };
