// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagSeverity } from "./DiagSeverity";

export type Diagnostic = { severity: DiagSeverity, message: string, 
/**
 * Файл от корня хранилища (`/Сеть/SSH.typ`) или пакета (`@preview/cetz:0.4.2/…`).
 */
file: string | null, 
/**
 * Строка и столбец с единицы.
 */
line: number | null, column: number | null, hints: Array<string>, };
