// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A graph edge: links from one node to another.
 */
export type Edge = { 
/**
 * Source node.
 */
from: string, 
/**
 * Target node.
 */
to: string, 
/**
 * How many links (with different anchors) go along this edge.
 */
count: number, 
/**
 * Not a link but a book to its chapter (the graph with chapters).
 */
chapter: boolean, };
