// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Edge = { from: string, to: string, 
/**
 * Сколько ссылок (с разными якорями) ведёт по этому ребру.
 */
count: number, 
/**
 * Не ссылка, а книга - её глава (граф с главами).
 */
chapter: boolean, };
