// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteId } from "./NoteId";
import type { NoteKind } from "./NoteKind";

/**
 * A note or a book in the vault.
 */
export type Entry = { id: NoteId, kind: NoteKind, };
