// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostic } from "./Diagnostic";

/**
 * An error body. `errors` are compile errors (for a PDF), otherwise empty.
 */
export type ErrorResponse = { error: string, errors: Array<Diagnostic>, };
