// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostic } from "./Diagnostic";

/**
 * Тело ошибки. `errors` — ошибки компиляции (у PDF), иначе пусто.
 */
export type ErrorResponse = { error: string, errors: Array<Diagnostic>, };
