// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeEvent } from "./ChangeEvent";

/**
 * The answer to `GET /api/vaults/{vault}/events?after=<seq>` (long polling, see `events`).
 */
export type EventsResponse = { 
/**
 * The server watches the files: waiting for changes makes sense. If not,
 * changes come only on the button.
 */
watching: boolean, 
/**
 * The number of the last change: `after` of the next request.
 */
seq: number, 
/**
 * Changes after `after`; empty if there were none (or no `after` in the request).
 */
changes: Array<ChangeEvent>, };
