// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeEvent } from "./ChangeEvent";

/**
 * Ответ `GET /api/vaults/{хранилище}/events?after=<seq>` (долгий опрос, см. `events`).
 */
export type EventsResponse = { 
/**
 * Сервер следит за файлами: ждать изменений есть смысл. Нет - изменения
 * только по кнопке.
 */
watching: boolean, 
/**
 * Номер последнего изменения - `after` следующего запроса.
 */
seq: number, 
/**
 * Изменения после `after`; пусто - их не было (или запрос без `after`).
 */
changes: Array<ChangeEvent>, };
