// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Первое событие `hello` потока `GET /api/vaults/{хранилище}/events`.
 */
export type EventsHello = { 
/**
 * Сервер следит за файлами: события `change` будут. Иначе — только
 * опрос версии.
 */
watching: boolean, };
