// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An item of `GET /api/vaults/{vault}/folders`: a folder with notes or an
 * empty one (`Vault::folders`).
 */
export type FolderListItem = { 
/**
 * The path from the root: `Network/Linux`.
 */
path: string, 
/**
 * The display title: from `_folder.toml`, otherwise the folder name.
 */
title: string, };
