// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Элемент `GET /api/vaults/{хранилище}/folders`: папка, в которой есть
 * заметки (или папки с ними).
 */
export type FolderListItem = { 
/**
 * Путь от корня: `Сеть/Linux`.
 */
path: string, 
/**
 * Название для показа: из `_folder.toml`, иначе — имя папки.
 */
title: string, };
