// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Layout forces in percent of the normal ones; by default folders hold
 * together a little (`clusters` 5 %, user's decision), the rest is normal.
 */
export type Forces = { 
/**
 * How pronounced folders are: the nodes of a folder hold together,
 * other folders repel more (a gap between folders); 0 - folders hold
 * together only by their starting places and links.
 */
clusters: number, 
/**
 * Pull to the center: less - a roomier graph.
 */
center: number, 
/**
 * Node repulsion.
 */
repel: number, 
/**
 * Pull of linked nodes (edge stiffness).
 */
links: number, };
