// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A piece of a fragment: a match or the text between matches.
 */
export type Fragment = { 
/**
 * The text.
 */
text: string, 
/**
 * Whether it is a match.
 */
hit: boolean, };
