// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Кусок фрагмента: совпадение или текст между совпадениями.
 */
export type Fragment = { text: string, hit: boolean, };
