// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge";
import type { Node } from "./Node";

/**
 * The link graph of a vault.
 */
export type Graph = { 
/**
 * Nodes in the order of their ids.
 */
nodes: Array<Node>, 
/**
 * Edges in the order of (from, to).
 */
edges: Array<Edge>, };
