// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge";
import type { PlacedNode } from "./PlacedNode";

/**
 * A graph ready to draw.
 */
export type GraphLayout = { 
/**
 * Placed nodes.
 */
nodes: Array<PlacedNode>, 
/**
 * Edges between them.
 */
edges: Array<Edge>, 
/**
 * All groups of the vault in order, for colors: a filter does not recolor nodes.
 */
groups: Array<string>, 
/**
 * Bounds of the drawing with labels: `[x0, y0, x1, y1]`.
 */
bounds: [number, number, number, number], 
/**
 * The note in the center ("neighbours of a note").
 */
center: string | null, };
