// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge";
import type { PlacedNode } from "./PlacedNode";

/**
 * Граф, готовый к рисованию.
 */
export type GraphLayout = { nodes: Array<PlacedNode>, edges: Array<Edge>, 
/**
 * Все группы хранилища по порядку — для цветов: фильтр не перекрашивает узлы.
 */
groups: Array<string>, 
/**
 * Границы нарисованного с подписями: `[x0, y0, x1, y1]`.
 */
bounds: [number, number, number, number], 
/**
 * Заметка в центре («соседи заметки»).
 */
center: string | null, };
