// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Forces } from "./Forces";

/**
 * What to show. Empty `folders` - all folders.
 */
export type GraphFilter = { 
/**
 * Only these groups (top-level folders; the root is [`ROOT_GROUP`]).
 */
folders: Array<string>, 
/**
 * Only notes in this folder and its subfolders (path from the root: `Мат/Анализ`).
 */
folder: string | null, 
/**
 * Hidden groups.
 */
hidden: Array<string>, 
/**
 * Only notes with this tag.
 */
tag: string | null, 
/**
 * Show missing notes (linked to but not written).
 */
missing: boolean, 
/**
 * Show notes without links.
 */
orphans: boolean, 
/**
 * Only the neighbours of this note within `depth` steps (both ways);
 * the note itself stays even if another filter would hide it.
 */
around: string | null, 
/**
 * Steps from `around`.
 */
depth: number, 
/**
 * Books as a root with chapters around it, not one node.
 */
chapters: boolean, 
/**
 * Layout forces (view settings on the graph page); a graph in a note
 * uses the defaults.
 */
forces: Forces, };
