// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Что показать. Пустой `folders` — все папки.
 */
export type GraphFilter = { 
/**
 * Только эти группы (папки верхнего уровня; корень — [`ROOT_GROUP`]).
 */
folders: Array<string>, 
/**
 * Скрытые группы.
 */
hidden: Array<string>, 
/**
 * Только заметки с этим тегом.
 */
tag: string | null, 
/**
 * Показывать несуществующие заметки (на них ссылаются, но их нет).
 */
missing: boolean, 
/**
 * Показывать заметки без связей.
 */
orphans: boolean, 
/**
 * Только соседи этой заметки на `depth` шагов (в обе стороны); она
 * сама остаётся, даже если её скрыл бы другой фильтр.
 */
around: string | null, depth: number, };
