// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Heading = { 
/**
 * Уровень оформления: 1 — глава книги, 2 — раздел, …
 */
level: number, id: string, 
/**
 * Слаг текста заголовка — по нему ссылка находит раздел.
 */
anchor: string, text: string, };
