// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Heading = { 
/**
 * The design level: 1 is a book chapter, 2 a section, ...
 */
level: number, id: string, 
/**
 * The slug of the heading text: a link finds the section by it.
 */
anchor: string, text: string, 
/**
 * Heading HTML for the contents (formulas, emphasis) without the number
 * and links; `None` for a plain-text heading (`passes::heading_html`).
 */
html?: string, };
