// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Choice } from "./Choice";

export type Kind = { "type": "bool" } | { "type": "number", min: number, max: number, step: number, } | { "type": "choice", options: Array<Choice>, } | { "type": "text", placeholder: string, };
