// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ссылка из заметки, как она написана в `#см(…)`.
 */
export type LinkRef = { target: string, anchor: string | null, };
