// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteId } from "./NoteId";

/**
 * A note whose links get rewritten.
 */
export type LinkRewrite = { note: NoteId, 
/**
 * How many links it has.
 */
count: number, };
