// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A link from a note as written in `#see(...)`.
 */
export type LinkRef = { target: string, anchor: string | null, };
