// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backlink } from "./Backlink";
import type { OutgoingLink } from "./OutgoingLink";

/**
 * `GET /api/links/{id}`.
 */
export type LinksResponse = { outgoing: Array<OutgoingLink>, backlinks: Array<Backlink>, };
