// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteId } from "./NoteId";

/**
 * Заметка, в которой перепишутся ссылки.
 */
export type LinkRewrite = { note: NoteId, 
/**
 * Сколько ссылок в ней.
 */
count: number, };
