// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/login`.
 */
export type LoginRequest = { login: string, password: string, };
