// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChapterOf } from "./ChapterOf";
import type { NoteKind } from "./NoteKind";

/**
 * A graph node: a note, a book, a book chapter or a missing note.
 */
export type Node = { 
/**
 * Note path; for a book chapter `<book>/.<number>` (a segment starting
 * with `.` is impossible in a note path).
 */
id: string, 
/**
 * `None`: the note does not exist (it is linked to but not written).
 */
kind: NoteKind | null, 
/**
 * Title ([`Snapshot::title`]); for a chapter, its heading.
 */
title: string, 
/**
 * A book chapter (the graph with chapters, [`Snapshot::graph_of`]).
 */
chapter: ChapterOf | null, };
