// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteKind } from "./NoteKind";

export type Node = { id: string, 
/**
 * `None` — заметки нет (на неё ссылаются, но её не написали).
 */
kind: NoteKind | null, };
