// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChapterOf } from "./ChapterOf";
import type { NoteKind } from "./NoteKind";

export type Node = { 
/**
 * Путь заметки; у главы книги — `<книга>/.<номер>` (сегмент на `.` в
 * пути заметки невозможен).
 */
id: string, 
/**
 * `None` — заметки нет (на неё ссылаются, но её не написали).
 */
kind: NoteKind | null, 
/**
 * Название ([`Snapshot::title`]); у главы — её заголовок.
 */
title: string, 
/**
 * Глава книги (граф с главами, [`Snapshot::graph_of`]).
 */
chapter: ChapterOf | null, };
