// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteId } from "./NoteId";
import type { NoteKind } from "./NoteKind";

/**
 * Элемент `GET /api/notes`.
 */
export type NoteListItem = { id: NoteId, kind: NoteKind, 
/**
 * Последний сегмент пути: `SSH` для `Сеть/SSH`.
 */
name: string, 
/**
 * Папка: `Сеть`; для корня — пустая строка.
 */
folder: string, };
