// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteId } from "./NoteId";
import type { NoteKind } from "./NoteKind";
import type { TaggedChapter } from "./TaggedChapter";

/**
 * An item of `GET /api/vaults/{vault}/notes`.
 */
export type NoteListItem = { id: NoteId, kind: NoteKind, 
/**
 * The last path segment, the file name: `SSH` for `Network/SSH`.
 */
name: string, 
/**
 * The folder: `Network`; an empty string for the root.
 */
folder: string, 
/**
 * The display title: from the template (`title: [...]`), otherwise the file name.
 */
title: string, 
/**
 * The note tags; for a book, those of its root (`main.typ`), inherited by every chapter.
 */
tags: Array<string>, 
/**
 * The book chapters with their own tags.
 */
chapters: Array<TaggedChapter>, };
