// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A note path from the vault root, without `.typ`, separated by `/`: `Network/SSH`.
 *
 * It is checked on creation, so a path inside the vault can always be safely
 * derived from it (no `..`, absolute paths or internal directories).
 */
export type NoteId = string;
