// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteId } from "./NoteId";
import type { NoteKind } from "./NoteKind";
import type { TaggedChapter } from "./TaggedChapter";

/**
 * Элемент `GET /api/vaults/{хранилище}/notes`.
 */
export type NoteListItem = { id: NoteId, kind: NoteKind, 
/**
 * Последний сегмент пути — имя файла: `SSH` для `Сеть/SSH`.
 */
name: string, 
/**
 * Папка: `Сеть`; для корня — пустая строка.
 */
folder: string, 
/**
 * Название для показа: из шаблона (`title: […]`), иначе — имя файла.
 */
title: string, 
/**
 * Теги заметки; у книги — корня (`main.typ`), их наследуют все главы.
 */
tags: Array<string>, 
/**
 * Главы книги со своими тегами.
 */
chapters: Array<TaggedChapter>, };
