// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Путь заметки от корня хранилища без `.typ`, через `/`: `Сеть/SSH`.
 *
 * Проверяется при создании, поэтому из него всегда можно безопасно
 * получить путь внутри хранилища (без `..`, абсолютных путей и служебных
 * каталогов).
 */
export type NoteId = string;
