// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookView } from "./BookView";
import type { Diagnostic } from "./Diagnostic";
import type { NoteId } from "./NoteId";
import type { NoteKind } from "./NoteKind";
import type { Rendered } from "./Rendered";

/**
 * A note ready to be shown.
 */
export type NotePage = { id: NoteId, kind: NoteKind, 
/**
 * The version of the note files and rendering settings.
 */
version: string, 
/**
 * The last good rendering. On a compile error, the previous good one (if
 * any): the reader sees the note with the error over it.
 */
rendered: Rendered | null, errors: Array<Diagnostic>, warnings: Array<Diagnostic>, 
/**
 * A book by chapters: which chapter is in `rendered` and where the others
 * are. Only in the answer to a chapter request ([`crate::book::chapter_page`]);
 * `None` for a whole page.
 */
book: BookView | null, };
