// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookView } from "./BookView";
import type { Diagnostic } from "./Diagnostic";
import type { NoteId } from "./NoteId";
import type { NoteKind } from "./NoteKind";
import type { Rendered } from "./Rendered";

/**
 * Заметка, готовая к показу.
 */
export type NotePage = { id: NoteId, kind: NoteKind, 
/**
 * Версия файлов заметки и настроек отрисовки.
 */
version: string, 
/**
 * Последняя удачная отрисовка. При ошибке компиляции — предыдущая
 * удачная (если была): читатель видит заметку и ошибку поверх неё.
 */
rendered: Rendered | null, errors: Array<Diagnostic>, warnings: Array<Diagnostic>, 
/**
 * Книга по главам: какая глава в `rendered` и где остальные. Только у
 * ответа на запрос главы ([`crate::book::chapter_page`]); у страницы
 * целиком — `None`.
 */
book: BookView | null, };
