// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A link from a note and whether its target exists.
 */
export type OutgoingLink = { target: string, anchor: string | null, exists: boolean, };
