// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ссылка из заметки и есть ли её цель.
 */
export type OutgoingLink = { target: string, anchor: string | null, exists: boolean, };
