// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteKind } from "./NoteKind";

/**
 * Узел на месте.
 */
export type PlacedNode = { id: string, 
/**
 * `None` — заметки нет.
 */
kind: NoteKind | null, 
/**
 * Подпись: последний сегмент пути.
 */
name: string, group: string, x: number, y: number, 
/**
 * Радиус кружка: книга крупнее, связи прибавляют.
 */
r: number, 
/**
 * Связей в показанном графе.
 */
degree: number, };
