// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChapterOf } from "./ChapterOf";
import type { NoteKind } from "./NoteKind";

/**
 * A node in its place.
 */
export type PlacedNode = { 
/**
 * Node id ([`Node::id`]).
 */
id: string, 
/**
 * `None`: the note does not exist.
 */
kind: NoteKind | null, 
/**
 * A book chapter: the book opens at this chapter.
 */
chapter: ChapterOf | null, 
/**
 * Label: the note title.
 */
name: string, 
/**
 * Group ([`group_of`]).
 */
group: string, 
/**
 * Center x.
 */
x: number, 
/**
 * Center y.
 */
y: number, 
/**
 * Circle radius: a book is larger, links add to it.
 */
r: number, 
/**
 * Links in the shown graph.
 */
degree: number, };
