// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteId } from "./NoteId";
import type { NoteKind } from "./NoteKind";

/**
 * Превью заметки для подсказки при наведении на ссылку.
 */
export type Preview = { id: NoteId, kind: NoteKind, title: string, 
/**
 * Раздел, на который ведёт ссылка (если якорь нашёлся).
 */
heading: string | null, 
/**
 * Начало текста раздела (или заметки), до `PREVIEW` символов.
 */
text: string, tags: Array<string>, };
