// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteId } from "./NoteId";
import type { NoteKind } from "./NoteKind";

/**
 * Preview of a note for the tooltip over a link.
 */
export type Preview = { 
/**
 * The note.
 */
id: NoteId, 
/**
 * Note or book.
 */
kind: NoteKind, 
/**
 * Note title (or file name).
 */
title: string, 
/**
 * The section the link leads to (if the anchor was found).
 */
heading: string | null, 
/**
 * The start of the section (or note) text, up to `PREVIEW` characters.
 */
text: string, 
/**
 * Tags of the note.
 */
tags: Array<string>, };
