// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenameKind } from "./RenameKind";

/**
 * `POST /api/vaults/{vault}/rename`: rename a note (a book) or a folder;
 * without `apply`, only the plan (the new path, which links get rewritten).
 */
export type RenameRequest = { kind: RenameKind, 
/**
 * The note or folder path.
 */
id: string, 
/**
 * The new title.
 */
title: string, apply: boolean, };
