// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PATCH /api/vaults/{vault}`: the new vault name.
 */
export type RenameVaultRequest = { name: string, };
