// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkRewrite } from "./LinkRewrite";
import type { RenameKind } from "./RenameKind";

/**
 * Что сделает переименование (или сделало).
 */
export type RenamePlan = { kind: RenameKind, 
/**
 * Прежний путь.
 */
from: string, 
/**
 * Новый путь: имя — из названия; совпадает с `from` — меняется только название.
 */
to: string, 
/**
 * Новое название (пробелы схлопнуты).
 */
title: string, 
/**
 * Другие заметки со ссылками сюда (у папки — на то, что в ней), по алфавиту.
 */
links: Array<LinkRewrite>, };
