// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkRewrite } from "./LinkRewrite";
import type { RenameKind } from "./RenameKind";

/**
 * What the rename will do (or did).
 */
export type RenamePlan = { kind: RenameKind, 
/**
 * The old path.
 */
from: string, 
/**
 * The new path: the name comes from the title; equal to `from` means only the title changes.
 */
to: string, 
/**
 * The new title (whitespace collapsed).
 */
title: string, 
/**
 * Other notes with links here (for a folder, to what is in it), in alphabetical order.
 */
links: Array<LinkRewrite>, };
