// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenameKind } from "./RenameKind";

/**
 * `POST /api/vaults/{хранилище}/rename`: переименовать заметку (книгу) или
 * папку; без `apply` — только план (новый путь, какие ссылки перепишутся).
 */
export type RenameRequest = { kind: RenameKind, 
/**
 * Путь заметки или папки.
 */
id: string, 
/**
 * Новое название.
 */
title: string, apply: boolean, };
