// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Heading } from "./Heading";
import type { LinkRef } from "./LinkRef";

export type Rendered = { title: string | null, 
/**
 * `<style>` from `<head>` (MathML styles from Typst).
 */
styles: string, 
/**
 * The contents of `<body>`.
 */
body: string, headings: Array<Heading>, links: Array<LinkRef>, tags: Array<string>, };
