// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchSection = { 
/**
 * `None` — начало заметки до первого заголовка.
 */
heading: string | null, 
/**
 * Якорь раздела (`#…`), как у отрисовки.
 */
anchor: string | null, text: string, };
