// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteId } from "./NoteId";
import type { NoteKind } from "./NoteKind";
import type { SearchSection } from "./SearchSection";

/**
 * Заметка в индексе поиска для клиента без сервера (статический сайт):
 * те же разделы, что ищет [`search`], — поиск по ним повторяет клиент
 * (`app/src/lib/site-search.ts`, те же правила и веса).
 */
export type SearchDoc = { id: NoteId, kind: NoteKind, 
/**
 * Название заметки (или имя файла).
 */
title: string, sections: Array<SearchSection>, };
