// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fragment } from "./Fragment";
import type { NoteId } from "./NoteId";
import type { NoteKind } from "./NoteKind";

/**
 * A search result: a section of a note.
 */
export type SearchHit = { 
/**
 * The note.
 */
id: NoteId, 
/**
 * Note or book.
 */
kind: NoteKind, 
/**
 * Note title (or file name).
 */
title: string, 
/**
 * The section where it was found; `None` - the start of the note.
 */
heading: string | null, 
/**
 * Section anchor for the link (`#...`).
 */
anchor: string | null, 
/**
 * Text around the matches.
 */
snippet: Array<Fragment>, 
/**
 * Weight: higher is better.
 */
score: number, };
