// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fragment } from "./Fragment";
import type { NoteId } from "./NoteId";
import type { NoteKind } from "./NoteKind";

export type SearchHit = { id: NoteId, kind: NoteKind, 
/**
 * Название заметки (или имя файла).
 */
title: string, 
/**
 * Раздел, где нашлось; `None` — начало заметки.
 */
heading: string | null, 
/**
 * Якорь раздела для ссылки (`#…`).
 */
anchor: string | null, snippet: Array<Fragment>, score: number, };
