// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The answer of `GET /api/session`.
 */
export type SessionResponse = { login: string, };
