// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Apply } from "./Apply";
import type { Choice } from "./Choice";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * The description of one setting.
 */
export type SettingDef = { 
/**
 * `group.name`, for example `view.numbering`.
 */
key: string, label: string, help?: string, default: JsonValue, 
/**
 * How the client applies the setting to the page; `None` means the client
 * does it in its own code (theme, books, refresh) or it is for the server (figures).
 */
apply?: Apply, 
/**
 * A device setting: each device has its own, not synced.
 */
device?: boolean, 
/**
 * A change from the interface goes to all vaults by default (theme, font
 * size: the user's decision), not only to the open one; a vault can set
 * its own. The others are the other way round (see the module).
 */
shared?: boolean, 
/**
 * A warning next to the setting: why it is dangerous.
 */
warning?: string, } & ({ "type": "bool" } | { "type": "number", min: number, max: number, step: number, } | { "type": "choice", options: Array<Choice>, } | { "type": "text", placeholder: string, });
