// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Choice } from "./Choice";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Описание одной настройки.
 */
export type SettingDef = { 
/**
 * `группа.имя`, например `view.numbering`.
 */
key: string, label: string, help?: string, default: JsonValue, } & ({ "type": "bool" } | { "type": "number", min: number, max: number, step: number, } | { "type": "choice", options: Array<Choice>, });
