// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Apply } from "./Apply";
import type { Choice } from "./Choice";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Описание одной настройки.
 */
export type SettingDef = { 
/**
 * `группа.имя`, например `view.numbering`.
 */
key: string, label: string, help?: string, default: JsonValue, 
/**
 * Как клиент применяет настройку к странице; `None` — сам, в своём коде
 * (тема, книги, обновление) или она для сервера (рисунки).
 */
apply?: Apply, 
/**
 * Настройка устройства: своя у каждого устройства, не синхронизируется.
 */
device?: boolean, } & ({ "type": "bool" } | { "type": "number", min: number, max: number, step: number, } | { "type": "choice", options: Array<Choice>, });
