// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Schema } from "./Schema";

/**
 * `GET /api/settings`.
 */
export type SettingsResponse = { schema: Schema, 
/**
 * Key -> a number, a string or a flag (the type is in the schema).
 */
values: Record<string, number | string | boolean>, };
