// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the vault settings file was not loaded (shown in the interface).
 */
export type SettingsProblem = { path: string, 
/**
 * The error text (English, from the parser or the disk).
 */
message: string, 
/**
 * Where the JSON error is (1-based), if the parser knows.
 */
line?: number, column?: number, };
