// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Schema } from "./Schema";

/**
 * `GET /api/settings`.
 */
export type SettingsResponse = { schema: Schema, 
/**
 * Ключ → число, строка или флаг (тип — по схеме).
 */
values: Record<string, number | string | boolean>, };
