// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The answer of `POST /api/device/sync/login`.
 */
export type SyncAccount = { 
/**
 * The complete address that was saved.
 */
server: string, login: string, 
/**
 * Plain `http://` to a host that is not this computer: the password and
 * the notes travel unencrypted.
 */
insecure: boolean, };
