// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/device/sync/login`.
 */
export type SyncLogin = { 
/**
 * The address of the storage server; `https://` is assumed without a scheme.
 */
server: string, login: string, password: string, };
