// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncHeldSide } from "./SyncHeldSide";

/**
 * A set of deletions the sync stopped at.
 */
export type SyncHeld = { 
/**
 * Where they would happen.
 */
side: SyncHeldSide, 
/**
 * How many files.
 */
count: number, 
/**
 * Of how many in the vault.
 */
total: number, };
