// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a round did: the answer of `link` and `now`, and `report` of a vault.
 */
export type SyncReport = { uploaded: number, downloaded: number, removed_local: number, removed_remote: number, 
/**
 * Files changed on both sides; settled by the setting `device.sync_prefer`.
 */
conflicts: Array<string>, 
/**
 * Files not synced in this round (too large, ...).
 */
skipped: Array<string>, };
