// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a linked vault's worker is doing (`idle` for one that is not linked).
 */
export type SyncState = "idle" | "syncing" | "error" | "sign-in" | "offline";
