// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncHeld } from "./SyncHeld";
import type { SyncReport } from "./SyncReport";
import type { SyncState } from "./SyncState";

/**
 * A vault in [`SyncStatus`].
 */
export type SyncVault = { name: string, 
/**
 * The folder exists on this device.
 */
local: boolean, 
/**
 * The vault is on the server; `null`: not known (see `server_error`).
 */
remote: boolean | null, linked: boolean, state: SyncState, 
/**
 * When the last round ended, Unix seconds.
 */
last_sync: number | null, 
/**
 * Why the last round failed, or what the worker is waiting for.
 */
error: string | null, 
/**
 * What the last successful round did.
 */
report: SyncReport | null, 
/**
 * The deletions that wait for `confirm` or `restore` (state `held`).
 */
held: SyncHeld | null, };
