// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncVault } from "./SyncVault";

/**
 * `GET /api/device/sync`.
 */
export type SyncStatus = { 
/**
 * The storage server of the saved account.
 */
server: string | null, login: string | null, signed_in: boolean, 
/**
 * Why the server's vault list is unknown (unreachable, session ended).
 */
server_error: string | null, 
/**
 * The server refuses the saved session: sign in again.
 */
session_ended: boolean, 
/**
 * Every vault of this device, of the account on the server and every
 * linked one, in alphabetical order.
 */
vaults: Array<SyncVault>, };
