// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Глава книги со своими тегами — для списка заметок и страницы тегов.
 */
export type TaggedChapter = { title: string, 
/**
 * `id` заголовка главы: ссылка `…/n/<книга>#<anchor>` открывает главу.
 */
anchor: string, 
/**
 * Свои теги главы; теги корня книги (`Outline::tags`) она наследует.
 */
tags: Array<string>, };
