// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A book chapter with its own tags, for the note list and the tags page.
 */
export type TaggedChapter = { 
/**
 * Chapter heading.
 */
title: string, 
/**
 * `id` of the chapter heading: the link `.../n/<book>#<anchor>` opens the chapter.
 */
anchor: string, 
/**
 * Own tags of the chapter; it inherits the tags of the book root (`Outline::tags`).
 */
tags: Array<string>, };
