// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Theme = { 
/**
 * Имя в `theme.typ` — значение настройки и `data-theme`.
 */
name: string, 
/**
 * Название для интерфейса.
 */
title: string, 
/**
 * Тёмная ли тема (по светлоте фона) — для выбора «как в системе».
 */
dark: boolean, };
