// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A theme for the settings and the client.
 */
export type Theme = { 
/**
 * Name in `theme.typ`: the setting value and `data-theme`.
 */
name: string, 
/**
 * Title for the interface.
 */
title: string, 
/**
 * Whether the theme is dark (by background lightness), for the theme "auto".
 */
dark: boolean, };
