// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VaultName } from "./VaultName";

/**
 * `GET /api/vaults`, ответ `POST /api/vaults`. Хранилища по умолчанию нет:
 * какое открыть, решает клиент (открытое последним) или пользователь.
 */
export type VaultsResponse = { 
/**
 * Все хранилища по алфавиту (может не быть ни одного).
 */
vaults: Array<VaultName>, 
/**
 * Можно ли создать новое (нельзя, если сервер открыт на одном
 * хранилище: `notes serve --vault <путь>`).
 */
can_create: boolean, };
