// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VaultName } from "./VaultName";

/**
 * `GET /api/vaults`, the answer to `POST /api/vaults`. There is no default
 * vault: the client (the last opened one) or the user decides which to open.
 */
export type VaultsResponse = { 
/**
 * All vaults in alphabetical order (there may be none).
 */
vaults: Array<VaultName>, 
/**
 * Whether a new one can be created (not when the server runs on one
 * vault: `notes serve --vault <path>`).
 */
can_create: boolean, };
