// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Schema } from "./Schema";

/**
 * `GET`/`PUT /api/vaults/{хранилище}/settings`: настройки для хранилища —
 * итог (`values`) и откуда он: общие для всех (`shared`) и заданные только
 * в этом хранилище (`own`).
 */
export type VaultSettingsResponse = { schema: Schema, values: Record<string, number | string | boolean>, shared: Record<string, number | string | boolean>, own: Record<string, number | string | boolean>, };
