// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A vault name, which is also the name of its folder. It is checked on
 * creation, so a path in the vaults directory can always be safely derived from it.
 */
export type VaultName = string;
