// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Имя хранилища — оно же имя его папки. Проверяется при создании: из него
 * всегда можно безопасно получить путь в каталоге хранилищ.
 */
export type VaultName = string;
