// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Schema } from "./Schema";
import type { SettingsProblem } from "./SettingsProblem";

/**
 * `GET`/`PUT /api/vaults/{vault}/settings`: settings for the vault - the
 * result (`values`) and where it comes from: shared by all (`shared`) and set
 * only in this vault (`own`).
 */
export type VaultSettingsResponse = { schema: Schema, values: Record<string, number | string | boolean>, shared: Record<string, number | string | boolean>, own: Record<string, number | string | boolean>, 
/**
 * The vault's settings file is broken: changes are not saved until it is fixed.
 */
problem?: SettingsProblem, };
