// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/vaults/{vault}/warm`: what to build ahead first (notes in tabs,
 * recent ones). Unknown and invalid paths are skipped.
 */
export type WarmRequest = { ids: Array<string>, };
