// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/warm`: что собрать заранее первым (заметки во вкладках,
 * недавние). Неизвестные и неверные пути пропускаются.
 */
export type WarmRequest = { ids: Array<string>, };
